services:
  ai-app:
    build: .
    container_name: nova-ai
    ports:
      - "https://nova-app-30ha.onrender.com"
    depends_on:
      - llm

  llm:
    image: jayanthkopparthi/cloud_app-ai-app:latest
    container_name: nova-llm
    environment:
      MODEL: ai/gemma3
    ports:
      - "https://nova-app-30ha.onrender.com"
